---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: true
  customize:
    cpus: 1
    memory: 512
  ssh:
    insert_key: false

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: 12.16.42

platforms:
- name: centos-6.8
  run_list: ['recipe[yum-epel]']
  driver_config:
    box: bento/centos-6.8
- name: centos-7.2
  run_list: ['recipe[yum-epel]']
  driver_config:
    box: bento/centos-7.2
- name: ubuntu-12.04
  run_list: ['recipe[apt]']
  driver_config:
    box: bento/ubuntu-12.04
- name: ubuntu-14.04
  run_list: ['recipe[apt]']
  driver_config:
    box: bento/ubuntu-14.04
- name: ubuntu-16.04
  run_list: ['recipe[apt]']
  driver_config:
    box: bento/ubuntu-16.04

suites:
- name: default
  run_list: ['recipe[rsc_mongo::default]']
  attributes:
    cloud:
      provider: vagrant
