---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpuexecutioncap: 50
#   natdnshostresolver1: "on"
# network:
# - ["forwarded_port", {guest: 8080, host: 8080}]
# - ["forwarded_port", {guest: 8443, host: 8443, auto_correct: true}]

driver_config:
    use_vagrant_berkshelf_plugin: true
    require_chef_omnibus: true

provisioner:
  name: chef_zero
  #cookbook_path: ~/stash/rsc_mongodb

platforms:
- name: centos-6.5
  driver_config:
    box: opscode-centos-6.5
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.5_provisionerless.box

suites:
  - name: primary
    run_list:
      - recipe['rsc_mongodb::default']
    attributes:
