---
driver:
  name: vagrant

provisioner:
  #name: chef_solo
  name: chef_zero
  require_chef_omnibus: 12.4.0
  node_name: mongoDB-dev

platforms:
#  - name: ubuntu-14.04
#    run_list: []
#    driver_config:
#      box: opscode-ubuntu-14.04
#      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box
  - name: CentOS7
    run_list:
      - recipe[build-essential::default]


suites:
  - name: default
    run_list:
     - recipe[build-essential::default]
     - recipe[rsc_mongodb::default]
    attributes:
