---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: true
  customize:
    cpus: 1
    memory: 512
  ssh:
    insert_key: false

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  require_chef_omnibus: 12.16.42

platforms:
- name: centos-6.8
  run_list: ['recipe[yum-epel]']
  driver_config:
    box: bento/centos-6.8
- name: centos-7.2
  run_list: ['recipe[yum-epel]']
  driver_config:
    box: bento/centos-7.2
- name: ubuntu-12.04
  run_list: ['recipe[apt]']
  driver_config:
    box: bento/ubuntu-12.04
- name: ubuntu-14.04
  run_list: ['recipe[apt]']
  driver_config:
    box: bento/ubuntu-14.04
- name: ubuntu-16.04
  run_list: ['recipe[apt]']
  driver_config:
    box: bento/ubuntu-16.04

suites:
- name: default
  run_list: ['recipe[rsc_mongodb::default]']
  attributes:
    cloud:
      provider: vagrant
    mongodb:
      key_file_content: 'L7WCC5/eYkJ9Pp4yxF1mRZj7M8H8pT5JNVTqzKU+CqG6Rk5AIK0920ZM8xhG2igz
Y999MwIVylU8wLGOdtCRqg+1HrHf4UHQ03Q99lsekKhHeTKyjRUgJSpGC21Y4l8g
/EBM3d4S3Z4IEHTK3bQC6dfGonyuFR4sBem2YLzK7x5Y5QmlhTvjbsk2Vu69qJIJ
dJwH5UFt+QYsnJYYfrqwoS1djvdsKg4z4eskOystnZZWLJBzUyTiMh3mNuyAJZb5
LN72khvfbUMm9vNTPgJYgoZEsQ+TiuyCoQqbq0Pi0MN9FmGp+js+ckOlQ2nNnKWv
mLeVyuHxABUCJuVigEgQ3DvEcT415GiGbBEOw87MGQd6iCpGwcNIiz1AYT2+b2Va
YWALHwm0Q+5DoKXbofPK/yXAEiZnflH4NdjcKfNxlgQ8+gVJ8DfY8ZWFe+kChbn0
LtZ7UeiO/gyYo/a4JLDliwDJQ6sxOvNaM9pbxFYyY5DixrXHd5DP4bKPWE4Bf6eG
cMyBZqn/Vs0LiorN6qK48W/7y4Yp550+IpdGqiPuYvRRDzkhXLZSE8bkCwiOBy//
u1+25RlR3l+QvISKXAcln+WA6xsGl24KIbM0pqmwc8BSbgI5CJQChpnJxB1qqTS4
kO/e9fuYCpLlwEndvjQmQVJYyCaCxqIWFRSUsN1UALqjPtuuPg/FCDd2H5WcAxip
jeI/2fhe0bVIQigNUIhf9WaSfmI61U6WPvxkHKSb2sCFkC6Q8X4YbE84AMgnMGtA
5dyIeOpo0L0hKHNy5WvZkUy7Ypcx7/t2HwezBAiP0Hb9x7j2/zhRSKeyVGSL9p1z
L+Jb97S3sZnM5mJyFiS9H0izRO9wQKUVDtd9eWph/y5iMLiBT8053TpG5LHVP3sC
h2DQlqRBKADyubO913h2G2dH8DdRPD/OQr7zGX1WCqLxdRMhupVGjU6M66qio6Vl
IwhJxnQmRTQF0ImiyylqiH+t4muLhxsEap34n0KVqflQ7zgR'

